name: 'Chromatic Deployment'

## Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # OS
    runs-on: ubuntu-latest
    # job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        # adds chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # options required for chromatic's github action
        with:
          # chromatic project token
          projectToken: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
          token: ${{secrets.MY_GITHUB_TOKEN}}